---
- hosts: pis
  become: yes
  remote_user: pi

  vars_files:
    - vars.yml
    - passwords.yml

  tasks:
    - name: Install avahi
      apt: name={{item}}
      with_items:
        - avahi-daemon
        - avahi-utils
        - avahi-dnsconfd
        - libavahi-core-dev
      
    - name: Set the current MAC address for wlan0.
      set_fact:
        cluster_mac_address: "{{ hostvars[inventory_hostname].ansible_wlan0.macaddress }}"

    - name: Set variables based on wlan0 MAC address.
      set_fact:
        cluster_hostname: "{{ mac_address_mapping[cluster_mac_address].name }}"
        cluster_ip_address: "{{ mac_address_mapping[cluster_mac_address].ip }}"

    - name: Set up networking-related files.
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ item.dest }}"
        mode: 0644
      with_items:
        - { template: hostname.j2, dest: /etc/hostname }
        - { template: hosts.j2, dest: /etc/hosts }
        - { template: interfaces.j2, dest: /etc/network/interfaces }
        - { template: wpa_supplicant.conf.j2, dest: /etc/wpa_supplicant/wpa_supplicant.conf }
        - { template: resolv.conf.j2, dest: /etc/resolv.conf }
        - { template: multiple.service.j2, dest: /etc/avahi/services/multiple.service }
      notify:
        - update hostname

    - name: Prevent Wifi from sleeping
      command: iw dev wlan0 set power_save off

  handlers:
    - name: update hostname
      command: "hostname {{ cluster_hostname }}"

    - name: avahi-daemon restarted
      service: name=avahi-daemon state=restarted enabled=yes
