---
- name: Configure ssh keys for root user
  authorized_key: user=root key=https://github.com/{{github_user}}.keys

# Source: http://forum.odroid.com/viewtopic.php?f=112&t=8075
- name: Copy resize FS
  copy: src=resizefs dest=/usr/local/bin/resizefs mode=0755 owner=root group=root

# - name: Resize partition
#   command: /usr/local/bin/resizefs
#   become_user: root

- name: Set up hostname files
  command: hostnamectl set-hostname {{ hostname }}

- name: Upgrade packages
  apt: update_cache=yes upgrade=yes
  when: ansible_os_family == "Debian"

- name: Upgrade packages
  pacman: update_cache=yes upgrade=yes
  when: ansible_os_family == "Archlinux"

- name: Install Zeroconf-related packages for easy network discovery w/o static IP
  package: name={{item}}
  with_items:
    - avahi
    - netatalk

- name: Set up avahi config files
  template:
    src: "multiple.service.j2"
    dest: "/etc/avahi/services/multiple.service"
    mode: 0644
  notify:
    - avahi-daemon restarted 

- name: Set up networking-related files.
  template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
